# Generated by Django 4.2.1 on 2023-05-21 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_lessons"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Lessons",
            new_name="Lesson",
        ),
    ]
