# Generated by Django 4.2.1 on 2023-05-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0006_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads"),
        ),
    ]
