# Generated by Django 4.2.1 on 2023-05-27 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0007_course_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="lsson_type",
            new_name="lesson_type",
        ),
    ]
